monolog:
    channels: ['telegram_request_in', 'telegram_request_out', 'dump']
    handlers:
        main:
            type: rotating_file
            path: '%kernel.logs_dir%/php/php-%kernel.environment%.log'
            level: error
            bubble: true
            max_files: 366

        telegram_request_in:
            type: rotating_file
            path: '%kernel.logs_dir%/tg/in/tg-in-%kernel.environment%.log'
            level: debug
            bubble: true
            max_files: 366
            channels: ['telegram_request_in']
            formatter: Monolog\Formatter\JsonFormatter

        telegram_request_out:
            type: rotating_file
            path: '%kernel.logs_dir%/tg/out/tg-out-%kernel.environment%.log'
            level: debug
            bubble: true
            max_files: 366
            channels: ['telegram_request_out']
            formatter: Monolog\Formatter\JsonFormatter

        dump:
            type: rotating_file
            path: '%kernel.logs_dir%/dump/dump-%kernel.environment%.log'
            level: debug
            bubble: true
            max_files: 366
            channels: ['dump']
            formatter: Monolog\Formatter\JsonFormatter