monolog:
    handlers:
        main:
            type: rotating_file
            path: '%kernel.logs_dir%/php/%kernel.environment%.log'
            level: error
            # max number of log files to keep
            # defaults to zero, which means infinite files
            max_files: 10
