parameters:
    locale: 'ru'

    # postgresql
    database_driver: '%env(DATABASE_DRIVER)%'
    database_host: '%env(DATABASE_HOST)%'
    database_port: '%env(DATABASE_PORT)%'
    database_name: '%env(DATABASE_NAME)%'
    database_user: '%env(DATABASE_USER)%'
    database_password: '%env(DATABASE_PASSWORD)%'
    server_version: '%env(SERVER_VERSION)%'

    root_path: '%kernel.project_dir%/public'
    base_url: '%env(BASE_URL)%'

    mailer_from: '%env(MAILER_FROM)%'
    mailer_from_name: '%env(MAILER_FROM_NAME)%'

    # telegram
    tg_token: '%env(TG_TOKEN)%'
    tg_admin_list: '%env(TG_ADMIN_LIST)%'
    tg_url: 'https://api.telegram.org/bot'
    tg_proxy:
    - '%env(PROXY_NAME)%'
    - '%env(PROXY_PORT)%'
    - '%env(PROXY_LOGPASS)%'

    # bitrix24
    bitrix24_base_url: '%env(BITRIX24_BASE_URL)%'
    bitrix24_url: '%env(BITRIX24_URL)%'
    bitrix24_api: '%env(BITRIX24_API)%'
    bitrix24_user_id: '%env(BITRIX24_USER_ID)%'

    # proxy
    proxy_name: '%env(PROXY_NAME)%'
    proxy_port: '%env(PROXY_PORT)%'
    proxy_logpass: '%env(PROXY_LOGPASS)%'

    # work_time
    work_time_start: '08:00'
    work_time_end: '21:00'
    # насколько дней вперед максимум можно забронировать
    date_range: 30

    # Добавляются и сортируются переговорки переменной meeting_room (при включенном auto_add добавляются автоматически,
    # но сортируются все равно здесь).
    # Название переговорки должно совпадать с названием календаря.
    # Переговорку можно скрыть, дописав в конце какие-нибудь символы, либо удалив полностью строку.
    # Сбросить кеш необходимо только после создания нового календаря. Для скрытия или сортировки не требуется.
    meeting_room: '%env(MEETING_ROOM)%'
    # Отображает все переговорки, к которому имеет доступ (сортировка работает и зависит от переменной meeting_room)
    meeting_room_auto_add: '%env(MEETING_ROOM_AUTO_ADD)%'
    # У гугла максимальная длина заголовка 1024, а описания (где хранятся списки участников) 16384
    # длина заголовка
    meeting_room_event_name_len: 128
    # 1 участник ~200 байт (1 участинк - 1 элемент массива со свойствами)
    # организатор не входит в список, но учитывается вместе с остальными в базе
    # (10 участников + 1 организатор) * ~200 байт = string 2200 байт необходимо для столбца в базе
    meeting_room_event_members_limit: 10
    # Длина имени и фамилии одного участника. Например $name = "Иван Иванов (НЛМК)"; strlen($name) == 18;
    meeting_room_event_members_len: 50

    # вклчюить / выключить оповещения
    notification_google: '%env(NOTIFICATION_GOOGLE)%'
    notification_mail: '%env(NOTIFICATION_MAIL)%'
    notification_telegram: '%env(NOTIFICATION_TELEGRAM)%'

    # Оповещение за хх мин. до начала события
    # Работает только для гугл-ящиков
    notification_time: 30

    # cache
    cache_time_google_calendar: 300
    cache_google_calendar: 'cache_google_calendar'
    cache_time_bitrix24: 300
    cache_bitrix24: 'cache_bitrix24'

    # анти-флуд
    # сообщений в минуту
    anti_flood_allowed_messages_number: 29

    google_service_account_email: '%env(GOOGLE_SERVICE_ACCOUNT_EMAIL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Monolog\Formatter\JsonFormatter: ~

    App\API\Telegram\Module\Admin:
        arguments:
            $tgAdminList: '%tg_admin_list%'
            $googleServiceAccountEmail: '%google_service_account_email%'
            $bitrix24BaseUrl: '%bitrix24_base_url%'

    App\API\Telegram\Module\AntiFlood:
        arguments:
            $allowedMessagesNumber: '%anti_flood_allowed_messages_number%'

    App\API\Telegram\Module\MeetingRoom:
        arguments:
            $dateRange: '%date_range%'
            $workTimeStart: '%work_time_start%'
            $workTimeEnd: '%work_time_end%'
            $eventNameLen: '%meeting_room_event_name_len%'
            $eventMembersLimit: '%meeting_room_event_members_limit%'
            $eventMembersLen: '%meeting_room_event_members_len%'
            $mailerFrom: '%mailer_from%'
            $mailerFromName: '%mailer_from_name%'
            $notificationMail: '%notification_mail%'
            $notificationTelegram: '%notification_telegram%'
            $notificationTime: '%notification_time%'
            $baseUrl: '%base_url%'


    App\API\Telegram\TelegramAPI:
        arguments:
            $tgUrl: '%tg_url%'
            $tgToken: '%tg_token%'
            $proxy: '%tg_proxy%'
            $tgLogger: '@monolog.logger.telegram_request_out'

    App\API\Bitrix24\Bitrix24API:
        arguments:
            $bitrix24Url: '%bitrix24_url%'
            $bitrix24UserId: '%bitrix24_user_id%'
            $bitrix24Api: '%bitrix24_api%'
            $cacheTime: '%cache_time_bitrix24%'
            $cacheContainer: '%cache_bitrix24%'

    App\API\GoogleCalendar\GoogleCalendarAPI:
        arguments:
            $notificationTime: '%notification_time%'
            $cacheTime: '%cache_time_google_calendar%'
            $cacheContainer: '%cache_google_calendar%'
            $dateRange: '%date_range%'
            $notificationGoogle: '%notification_google%'
            $meetingRoom: '%meeting_room%'
            $meetingRoomAutoAdd: '%meeting_room_auto_add%'